### PR TITLE
santoni: enable HAL3

### PR DESCRIPTION
**Pull request by ElebrUS**

### CODE REVIEW

**Comment by andreisaniuk** [comment]
`Xiaomi fked up, janky old camera blobs are returning inconsistent
supported preview frame rates in HAL3.

OpenCamera:
max preview fps returned by camera is 30.0, which is the default fps
OpenCamera requested. Recording works.

WhatsApp:
max preview fps returned by camera is 24.0 (whyyy???), however WhatsApp
requests for 30fps, which causes record breakage.

To avoid user from experiencing camera recording failure on HAL3,
disable it and force HAL1 which works in every use cases.

To enable HAL3 back, simply set persist.camera.HAL3.enabled=1 and
prepare to face any consequences that I just warned you about.

AND SCREW YOU XIAOMI`
Per this commit [https://github.com/nichcream/android_device_xiaomi_land/commit/8edb09c938f75add02f03aff1c5293651d843dce](url)

**Comment by andreisaniuk** [comment]
Can it be reproduced only in Whatsapp? For me recording works fine there

**Comment by nichcream** [comment]
There's Simple Camera that crashes too. IMO santoni is good to go with HAL3.. Let land suffer with the old MM camera blobs that Xiaomi refuse to update.

**Comment by andreisaniuk** [comment]
I  will check it in Simple camera then

**Comment by andreisaniuk** [comment]
Checked in Simple Camera too. Video recording works fine there too. Last thing to check is ViLTE I guess. But I do not have it in my country

**Pull request closed without merging**
